name: Fuzz APWorld
on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]


jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/ap-actions/fuzz@main
        with:
          apworld-path: .
          apworld-name: manual_thegrinchps1_mariospore
          ap-version: '0.6.1'
          python-version: '3.12'
