name: Release APWorld
on:
  push:
    tags:
      - '**'
jobs:
  release:
    uses: Eijebong/ap-actions/.github/workflows/release-apworld.yml@main
    with:
      apworld-path: .
      apworld-name: manual_thegrinchps1_mariospore
      ap-version: '0.6.1'
      python-version: '3.12'
